### ISSUE TITLE
Crates.io release

### ISSUE THREAD

**Issue by ianthetechie** [flother/spreet#34]
Thanks a bunch for making this project! It would be great if it were on crates.io as well for ease of installation on non-macOS platforms (like my CI/CD pipelines).

**Comment by flother** [comment]
Great idea, thanks for suggesting it. I've just put the [newly-released v0.5.0 up on crates.io](https://crates.io/crates/spreet). I'll leave this ticket open as a reminder I need to do a few more things:

- [ ] Document how to get Spreet via `cargo install` in the README
- [ ] Add the recommended metadata to `Cargo.toml` (e.g. `homepage`, `readme`)
- [ ] Automatically publish a new version to crates.io via the [GitHub Actions release workflow](https://github.com/flother/spreet/blob/master/.github/workflows/release.yml)
