### ISSUE TITLE
Convert all `.unwrap()` and similar panics to proper errors

### ISSUE THREAD

**Issue by nyurik** [flother/spreet#66]
Currently there are many `.unwrap()` calls that would cause a lib user to have an unexpected crash. I think `actix` web framework will handle when a URL path handler would crash, but clearly it would be better to have proper error handling instead.

I propose to add `thiserror`-implementing Error enums instead. Would that be ok?

**Comment by flother** [comment]
Funnily enough I did remove some of the `unwrap()`s just the other day (ae9a8e6e79 and edab806dfb), and I was thinking I should add thiserror while I was at it. But I got distracted working on #58 and never got round to it. Which is a long way of saying, yes, that would be more than OK 😄

**Comment by nyurik** [comment]
I just pushed #69 for this

**Comment by flother** [comment]
Closed by #69
