### ISSUE TITLE
Please rename primary branch to `main`

### ISSUE THREAD

**Issue by nyurik** [flother/spreet#70]
Github actually supports easy transition - just rename it, and it will create proper redirects

**Comment by flother** [comment]
As someone with little connection to the United States, I’ve only watched this debate from afar. I am of course aware of the very real problems this is aiming to address, but I’ve yet to see a convincing argument that this is anything other than a well-intended but ultimately empty (and etymologically-muddy) gesture

**Comment by nyurik** [comment]
well, a human language is just a way for people to "communicate by labels" - i say a word (a label of a concept), and that word means something to you.  If the word I say causes negative associations with the person who hears it, it gets in the way of communicating (that person will trip over the meaning, and think about their own feelings rather than simply understand the meaning and move on).  Think of this as a papercut - might be big or tiny depending on the listener, but why cause it if its easy not to?  I'm here (github) to collaborate on great software - if the choice of words repels even one participant, it is my loss :)

**Comment by nyurik** [comment]
and thank you :)
